{% set name = "panel-chemistry" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/panel-chemistry-{{ version }}.tar.gz
  sha256: af4d3f6d10830a10d65e6c0ef3a7f8a607ff630e0b7729b4fccb4f49da1b73c4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bokeh ==2.4.3
    - panel ==0.14.0
    - param >=1.12.0
    - python >=3.7

test:
  imports:
    - panel_chemistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awesome-panel/panel-chemistry
  summary: This package makes it easy to work with Chemistry using Python and HoloViz Panel
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MarcskovMadsen
    - awesome-panel
