{% set name = "panel-chemistry" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/panel-chemistry-{{ version }}.tar.gz
  sha256: b48e1e6719c694c07651bd39db9c0d9c3f04b9f79fc1b56427c00e273edc50a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bokeh >=2.4.2
    - panel >=0.12.7
    - param >=1.12.1
    - python >=3.7
    - numpy

test:
  imports:
    - panel_chemistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MarcSkovMadsen/panel-chemistry
  summary: This package makes it easy to work with Chemistry using Python and HoloViz Panel
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MarcSkovMadsen
    - Jhsmit
