{% set name = "panel-chemistry" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/panel-chemistry-{{ version }}.tar.gz
  sha256: 902557db8aeb60a85b5bac7cbd77c44aab33afce2255788ed7db6c36ab5dc701

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bokeh ==2.4.3
    - panel ==0.14.0
    - param >=1.12.0
    - python >=3.7
    - numpy

test:
  imports:
    - panel_chemistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awesome-panel/panel-chemistry
  summary: This package makes it easy to work with Chemistry using Python and HoloViz Panel
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MarcskovMadsen
    - awesome-panel
    - Jhsmit
